contact_links:
  - name: I have a question â“
    url: https://github.com/collerek/ormar/discussions
    about: If you have any question about the usage of ormar, please open a discussion first.
  - name: I want a new feature ğŸ†•
    url: https://github.com/collerek/ormar/discussions
    about: If you would like to request or make a change/enhancement that is not trivial, please open a discussion first.
